import 'package:flutter/material.dart';
import 'package:safe_vault/models/theme/AppColors.dart';

class AppThemes {
  static final ThemeData light = ThemeData(
    brightness: Brightness.light,
    fontFamily: "Montserrat",
    useMaterial3: true,
    extensions: [
      AppColors(
        text1: const Color(0xFFFFFFFF),
        text2: const Color(0xFF000000),
        text3: const Color(0xFF1F2937),
        text4: const Color(0xFF6B7280),
        text5: const Color(0xFF4B5563),
        hintText: const Color(0xFF979CA5),
        background: const Color(0xFFF1F5F9),
        containerBackground1: const Color(0xFFFFFFFF),
        containerBackground2: const Color(0xFFF9FAFB),
        dropShadow: const Color(0x1A000000),
        pinkLight: const Color(0xFFFDF2F8),
        orangeLight: const Color(0xFFFFF7ED),
        greenLight: const Color(0xFFF0FDF4),
        purpleLight: const Color(0xFFFAF5FF),
        pinkDarker: const Color(0xFFDB2777),
        orangeDarker: const Color(0xFFEA580C),
        greenDarker: const Color(0xFF16A34A),
        purpleDarker: const Color(0xFF9333EA),
        navbarIconsBackground: const Color(0xFFE2E8F0),
        navbarIconsColor: const Color(0xFF475569),
        gradientButtonsStart: const Color(0xFF673AB7),
        gradientButtonsEnd: const Color(0xFF512DA8),
        gradientButtonsUnavailableStart: const Color(0xFF673AB7).withAlpha(128),
        gradientButtonsUnavailableEnd: const Color(0xFF512DA8).withAlpha(128),
        gradientTopStart: const Color(0xFF673AB7),
        gradientTopEnd: const Color(0xFF512DA8),
      ),
    ],
  );

  static final ThemeData dark = ThemeData(
    brightness: Brightness.dark,
    fontFamily: "Montserrat",
    useMaterial3: true,
    extensions: [
      AppColors(
        text1: const Color(0xFFFFFFFF),
        text2: const Color(0xFFFFFFFF),
        text3: const Color(0xFFD7DDE6),
        text4: const Color(0xFFBBBBBB),
        text5: const Color(0xFFFFFFFF),
        hintText: const Color(0xFFB8B8B8),
        background: const Color(0xFF171717),
        containerBackground1: const Color(0xFF2C2C2C),
        containerBackground2: const Color(0xFF3C3C3C),
        dropShadow: const Color(0x1AFFFFFF),
        pinkLight: const Color(0xFFDB2777),
        orangeLight: const Color(0xFFEA580C),
        greenLight: const Color(0xFF16A34A),
        purpleLight: const Color(0xFF9333EA),
        pinkDarker: const Color(0xFFDB2777),
        orangeDarker: const Color(0xFFEA580C),
        greenDarker: const Color(0xFF16A34A),
        purpleDarker: const Color(0xFF9333EA),
        navbarIconsBackground: const Color(0xFF3C3C3C),
        navbarIconsColor: const Color(0xFFFFFFFF),
        gradientButtonsStart: const Color(0XFF4A2999),
        gradientButtonsEnd: const Color(0xFF46287C),
        gradientButtonsUnavailableStart: const Color(0xFF4A2999).withAlpha(128),
        gradientButtonsUnavailableEnd: const Color(0xFF46287C).withAlpha(128),
        gradientTopStart: const Color(0xFF46287C),
        gradientTopEnd: const Color(0xFF4A2999),
      ),
    ],
  );
}
